### ISSUE TITLE
Timestamp starts at 10H

### ISSUE THREAD

**Issue by WinggedPhantom** [irbyjm/trakt-discord-presence#9]
Timestamp is starting at 10 hours instead of 00 - https://gyazo.com/b18d11bbe160e1be5353dce27fba6bdc

**Comment by irbyjm** [comment]
This might be related to #8. I'm seeing weird results across both of my computers at home related to timestamp.

Are you GMT+/-10?

**Comment by WinggedPhantom** [comment]
Yes I am

**Comment by irbyjm** [comment]
This looks like it could be caused by the following code:
```python
os.environ['TZ']='UTC'

while True:
    try:
        watching = my.watching
        if watching:
            timestamp = int(time.mktime(time.strptime(watching.started_at[:-1]+"UTC", "%Y-%m-%dT%H:%M:%S.000%Z")))
```

If I change `os.environ['TZ']='UTC'` to `os.environ['TZ']='UTC-5'` then my elapsed time is off by 5 hours like so:
![image](https://user-images.githubusercontent.com/12702340/56780907-11f94f80-67af-11e9-9ab0-93124c4a4f6a.png)

I've tried something, will need a test (works fine for me so far).
